api:
  security:
    token:
      secret: ${JWT_SECRET:aolisughd97YASDGBAS&*D678astdagsba78das6dasd8ab}

spring:
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  application:
    name: MedVoll
  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
      sort:
        sort-parameter: ordem

  datasource:
    url: jdbc:mysql://localhost/vollmed_api
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    Mostrando as querys sql gerenciadas pelo Hibernate
    show-sql: true
    properties:
      hibernate:
#        Formatando sql gerado pelo Hibernate
        format_sql: true
  web:
    error:
      include-stacktrace: never

#server:
#  error:
#    include-stacktrace: never